language: php

php:
  - 5.3

env:
  global:
    # Your Pantheon site's UUID (e.g. from your dashboard URL)
    - PUUID='5d6c3b52-b516-46a2-870b-a6c9f0313c16'

    # Your Pantheon site's name.
    - PNAME='travis-test'

    # The Pantheon environment name from which Multidev DB/files will be pulled.
    # Probably one of: dev, test, live.
    - PENV='dev'
    - PSOURCE='dev'

    # The user you interact with Pantheon as
    - PEMAIL='kevin@bt48.com'

    # SECRET/PRIVATE VARIABLES
    #
    # These are created by using the travis command locally to encrypt some values.
    #
    # See: http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
    #
    # PEMAIL environment variable: represents the Pantheon account e-mail with
    # access to this site. Used to authenticate to Pantheon via Terminus. You
    # must cd to your project root and run:
    #
    # travis encrypt PEMAIL='test@example.com'
    #
    - secure: "WLuLiX+l7NuhvvjzAbCAZ5nPtPXYi5K7SQGIyYsmh3DjuhFAQmtUj3+X/jHkg483hJ+0Tud+IFvy10rhgZAS1mAZw7Y0viic/QezkOGXEj6PmdsCfA77+M+qASACro4TKDF8HRFUsVRP+xEKey8VhMuCmLuoeUEA0o4Zyg/kOHpGnfGxLvuVsvjO9F3W+5tUDwVOcq2J5CurOZaiRvUK4eubw/ADQr9hf/4mTJUVjgVG9k9KMSKoa95Ydg8XbuqEd32q0hUN7FBf6OgLjoiEIlC9zI4kBdElxp259f3nFyYZvTu1ATl/7xPKw/smcOmck7ma+utunY0fl4NyFKMwa5t1DKIPacdt8Hp53Dcrxm2DEzBLKTyXtfvwW4pxeHk5YukOvH8ajgvp7R4gRheFXYjf1mgYMznomD+LHX58kt2AYSRyjxMeLDWV1hkR97RBLaeXycQtXx+ZYnASnhUkOosDmCG2svv+McB+Qd/GcvRHBXqFLBKvi6ZS5pFf2SlItzxylur1gTeacdZJmPg+4Ws+f1UKRjHrIZFn/lPfQy1Non1yl/4a2pflEjLbx0qTQ/TnRxUi1hyMjHRZa7PB4MBFaEd0G9gjXY2ZwBWO8z7e3Zk7yxDFOOFwsPYc/9rhM6lbCsG33PHCD59tGsEsSG29vdQePmJZNPh9LDV3lX4="

    #
    # PPASS environment variable: represents the Pantheon account password for
    # the above encrypted e-mail address. Run:
    #
    # travis encrypt PPASS='my_account_password'
    #
    - secure: "rQyjiNuS5jcqdVSVrW1xvxUI6QbJbQf6pgSgteOiSxwnSUPQPMNUSbitIb+pFDxbcuR833l7IA9GcSmiAHL3S3hIBpmigLKc8Qe5d8IWCd0C3g3RX2h2xCtyKcdUnAtD+TUdEVPg1W+YJONWajGFKdGNhb6jXWQrrdvhihUSziyzCGr0VFCmktF2HR6gEKyCsDjv7HeplZvmyjvlX9wgemsOETu3aMCfiSM5uGxgx/1nColBkk/55DN3NARKFurvXTGDmf/bQo1D6mRnnA7Ge3PSZ2kLgOcab4hmy19zW9+rzwwzpo1g4hIZLtW0DNd7tKo4/dU163WzSd4ZG07YyXukMdMqGQadr+KwkpUAEFWpH4FZeZPiwTM9UnbLKOuEJeUx1LkLpV2Ta+QPkYge8U5vYX/bKnVf5ODePw9JuSP/L6paRbmtGYSy0Y4gNep5IFjHXAsGqfusVOX57BH0KvhdR1ggQuksmnnd8jDouJ9mgMUeVaGoFJkwV2wCzC2wNU/YZYT9xgbbHIe4cZah8GSfIc825cKaI3BV7QcErBcSIMX9cqJbWCodFtQCg8lgAN9Pd9fOCEybfFAzdL/WKnG8fd+R9f7vBkBgKFnLWfkq8VBLOspyfYpMICFzdwZ+Zz6mC1sHpTOx/tgSR6fiwFRIqtfTGhm2yt+huBV+kkA="

before_install:
    # Place a passphrase-free ssh key so that you can clone and push to your
    # Pantheon git repository.
    #
    # Use the travis encrypt-file command to generate your own.
    #
    # See: http://docs.travis-ci.com/user/encrypting-files/
    #
    - openssl aes-256-cbc -K $encrypted_e14e8e605e4c_key -iv $encrypted_e14e8e605e4c_iv -in travis-ci-key.enc -out ~/.ssh/id_rsa -d
    - chmod 0600 ~/.ssh/id_rsa


install:
    - sudo curl https://github.com/pantheon-systems/cli/releases/download/0.7.0/terminus.phar -L -o /usr/local/bin/terminus 
    - sudo chmod +x /usr/local/bin/terminus

before_script:
    - terminus cli version
    - terminus auth login $PEMAIL --password=$PPASS

script:
  # bash scripts/run_tests.sh

after_script:
  # General-purpose clean-up could go here.


after_success:
  # Maybe promote to test here?

after_failure:
  # Maybe roll back?

notifications:
  email:
    recipients:
      # - kevin@bt48.com
    on_success: always
    on_failure: always
